#!/usr/bin/env bash

while read file; do
    case "$1" in
        "w")
            xclip -selection clipboard -t image/png "$file"
            notify-send "Image $file copied to clipboard"
            ;;
        "k")
            rm "$file"
            notify-send "File $file deleted"
            ;;
    esac
done
