[font]
size = 13.0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "H"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Last"
key = "L"
mode = "Vi|~Search"
mods = "Shift"

[scrolling]
history = 1000

[window.dimensions]
columns = 80
lines = 22
